### ISSUE TITLE
EMLEntityView loads the wrong model attributes after multiple file additions

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#169]
When we choose multiple files using the `Add Files` button, each file is then added to the collection, however, an EMLOtherEntity object is not added to the EML211.entities array.  Instead, the code is creating a new EMLOtherEntity model on the fly based on the contents of the DataONEObject.  We have an index mismatch where the entity and attribute information for the incorrect entity is being loaded into the view when you choose to edit entity/attribute information for a newly added file.  Track this down.

**Comment by laurenwalker** [comment]
I pushed some changes yesterday that may be related to this issue. I was experiencing issues with saving DataONEObjects if they were added to the table in multiples rather than one at a time. I think my fix may have fixed this issue as well, so its worth looking at.

**Comment by csjx** [comment]
Hmm, I'm still seeing the index mismatch, so am continuing to work on it.  I also see another serialization issue when adding an entity to the EML, so I'm looking at that with this.

**Comment by csjx** [comment]
This is fixed. During `DataItemView.addFiles()` we add an `EMLEntity` instance into the `EML211.entities` array so the indexing is correct.  I'm seeing a different issue with attribute ids repeating, but will address that under #135.
