### ISSUE TITLE
Minor display issues in portal data tab

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1696]
**Describe the bug**

I saw a few minor display issues on https://search.dataone.org/portals/SASAP/Data. I couldn't find any open issues, apologies of this is a duplicate.

**To Reproduce**
1. Go to https://search.dataone.org/portals/SASAP/Data
2. See
  a. See form inputs have broken borders
  b. At wide widths, see the "People and Organization" tab looks odd compared to the other tabs

**Screenshots**

<img width="352" alt="Screen Shot 2021-03-22 at 5 46 39 PM" src="https://user-images.githubusercontent.com/563/112080432-da2fe980-8b36-11eb-9fe4-455a025ac758.png">
<img width="810" alt="Screen Shot 2021-03-22 at 5 46 47 PM" src="https://user-images.githubusercontent.com/563/112080436-db611680-8b36-11eb-9aa8-2cf50a429a9e.png">

macOS 11.2.3, Chrome 89.0.4389.90, Safari  14.0.3 (16610.4.3.1.7)

**Comment by robyngit** [comment]
Just a note that the broken borders in the form input are already fixed in the `develop` branch (since https://github.com/NCEAS/metacatui/issues/1636)

<img width="348" alt="Screen Shot 2021-03-24 at 14 45 00" src="https://user-images.githubusercontent.com/26600641/112366865-a5936d80-8caf-11eb-869e-7a00072a8c39.png">

**Comment by amoeba** [comment]
Ah, right. Thanks @robyngit. I'll leave this open since the other issue remains.
