### ISSUE TITLE
EMLParty validation error

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#337]
I copied a person to every single role available and clicked Submit. I got this EML validation error. It seems like an associatedParty is being inserted out of order in the EML.

`error updating EML:  <?xml version="1.0" encoding="UTF-8"?><error detailCode="1310" errorCode="500" name="ServiceFailure">
    <description>Error inserting or updating document: urn:uuid:9aa565bc-646a-4fd9-81cc-44835d87dd6b since &lt;?xml version="1.0"?&gt;&lt;error&gt;cvc-complex-type.2.4.a: Invalid content was found starting with element 'associatedParty'. One of '{contact, publisher, pubPlace, methods, project, dataTable, spatialRaster, spatialVector, storedProcedure, view, otherEntity}' is expected.&lt;/error&gt;</description>
</error>`

EML document:

```xml
<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:stmml="http://www.xml-cml.org/schema/stmml-1.1" xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 eml.xsd" packageId="urn:uuid:1377acf4-f4b2-479d-a5d3-5c56d830d22f" system="knb">
<dataset>
<alternateIdentifier>Dolore ieste ipsam nostrud elit</alternateIdentifier>
<title>Sed eu quaee earum nostrud</title>
<creator id="7550785610857253"><individualName><givenName>Lauren</givenName><surName>Walker</surName></individualName><userId directory="https://orcid.org">http://orcid.org/0000-0003-2192-431X</userId></creator><creator id="4220545002636341"><individualName><givenName>Bob</givenName><surName>Smith</surName></individualName></creator>
<associatedParty id="1014747996866850"><individualName><surName>Smith</surName></individualName><organizationName>lknsf</organizationName><positionName>onl</positionName><address><deliveryPoint>skdnf</deliveryPoint><deliveryPoint>q3knf</deliveryPoint></address><phone phonetype="facsimile">(123) 123 - 1234</phone><phone phonetype="voice">(123) 123 - 1234</phone><electronicMailAddress>dlkfn</electronicMailAddress><onlineUrl>sldfkn</onlineUrl><role>custodianSteward</role></associatedParty>
<associatedParty id="6072044431734188"><individualName><surName>Smith</surName></individualName><role>custodianSteward</role></associatedParty><associatedParty id="1522646129040858"><individualName><surName>Smith</surName></individualName><role>custodianSteward</role></associatedParty>
<associatedParty id="8532946422771486"><individualName><surName>Smith</surName></individualName><role>custodianSteward</role></associatedParty><associatedParty id="8832746337058653"><individualName><surName>Smith</surName></individualName><role>custodianSteward</role></associatedParty>
<pubDate>1986</pubDate>
<abstract><para>Laborioseam corporis numquam reprehenderit nostrud officia culpa enim anim dolor accusamus voluptas dignissimos ut</para></abstract>
<keywordSet><keyword>Hic animi neqeue molestias proident</keyword><keywordThesaurus>GCMD</keywordThesaurus></keywordSet>
<intellectualRights><para>This work is dedicated to the public domain under the Creative Commons Universal 1.0 Public Domain Dedication. To view a copy of this dedication, visit https://creativecommons.org/publicdomain/zero/1.0/.</para></intellectualRights>
<coverage>
     <geographicCoverage><geographicDescription>test</geographicDescription><boundingCoordinates><westBoundingCoordinate>23</westBoundingCoordinate><eastBoundingCoordinate>90</eastBoundingCoordinate><northBoundingCoordinate>90</northBoundingCoordinate><southBoundingCoordinate>90</southBoundingCoordinate></boundingCoordinates></geographicCoverage>
     <temporalCoverage><singleDateTime><calendarDate>1986</calendarDate></singleDateTime></temporalCoverage>
</coverage>
<contact id="5352507122878828"><individualName><givenName>Lauren</givenName><surName>Walker</surName></individualName><userId directory="https://orcid.org">http://orcid.org/0000-0003-2192-431X</userId></contact>
<associatedParty id="8200542778458541"><individualName><surName>Smith</surName></individualName><role>custodianSteward</role></associatedParty>
<associatedParty id="5338645117828675"><individualName><surName>Smith</surName></individualName><role>custodianSteward</role></associatedParty>
<project><title>Sed eu quaee earum nostrud</title><personnel id="2762116785534522"><individualName><givenName>Lauren</givenName><surName>Walker</surName></individualName><role>principalInvestigator</role></personnel><funding><para>Lorem quas sapienete ut esse officiis atque ut laborum Similique eu in exercitation dolore nostrud sint sed dolores eveniet praesentium</para></funding></project>
</dataset>
</eml:eml>
```

**Comment by ThomasThelen** [comment]
From the EML it looks like all of the people were added with `<role>custodianSteward</role>` (see formatted output below)

@laurenwalker Did you copy the user with id 1014747996866850 (the top one) to the other roles? If so it looks like we have an issue with party attributes copying over.
```
<creator id="7550785610857253"><individualName><givenName>Lauren</givenName><surName>Walker</surName></individualName><userId directory="https://orcid.org">http://orcid.org/0000-0003-2192-431X</userId></creator><creator id="4220545002636341"><individualName><givenName>Bob</givenName><surName>Smith</surName></individualName></creator>

<associatedParty id="1014747996866850">
    <individualName><surName>Smith</surName></individualName>
    <organizationName>lknsf</organizationName>
    <positionName>onl</positionName>
    <address><deliveryPoint>skdnf</deliveryPoint><deliveryPoint>q3knf</deliveryPoint></address>
    <phone phonetype="facsimile">(123) 123 - 1234</phone>
    <phone phonetype="voice">(123) 123 - 1234</phone>
    <electronicMailAddress>dlkfn</electronicMailAddress>
    <onlineUrl>sldfkn</onlineUrl>
    <role>custodianSteward</role>
</associatedParty>

<associatedParty id="6072044431734188">
    <individualName><surName>Smith</surName></individualName>
    <role>custodianSteward</role>
</associatedParty>
    
<associatedParty id="1522646129040858">
    <individualName><surName>Smith</surName></individualName>
    <role>custodianSteward</role>
</associatedParty>

<associatedParty id="8532946422771486">
    <individualName><surName>Smith</surName></individualName>
    <role>custodianSteward</role>
</associatedParty>

<associatedParty id="8832746337058653">
    <individualName><surName>Smith</surName></individualName>
    <role>custodianSteward</role>
</associatedParty>

<associatedParty id="8200542778458541">
    <individualName><surName>Smith</surName></individualName>
    <role>custodianSteward</role>
</associatedParty>

<associatedParty id="5338645117828675">
    <individualName><surName>Smith</surName></individualName>
    <role>custodianSteward</role>
</associatedParty>
```

**Comment by ThomasThelen** [comment]
Using parameters from `<associatedParty id="1014747996866850">`, I was unable to reproduce the error.

**Comment by ThomasThelen** [comment]
This should be fixed in #336

**Comment by laurenwalker** [comment]
I'm still experiencing this EML validation error after fixing #336, so Im reopening.
