### ISSUE TITLE
Links to external websites don't show the "Are you sure?" alert

### ISSUE THREAD

**Issue by isteves** [NCEAS/metacatui#550]
This behavior risks losing any edits that have not been previously saved.

<img width="683" alt="screen shot 2018-04-03 at 12 15 48 pm" src="https://user-images.githubusercontent.com/25118334/38270660-f0ec03e8-3738-11e8-8633-df5e7a5b3b2a.png">

**Comment by laurenwalker** [comment]
I also noticed that any link to a different webpage (outside of the backbone app) does not trigger the "are you sure?" message. This needs to be fixed as well as opening this link in a new window.

**Comment by vchendrix** [comment]
@laurenwalker  I just checkout out this change and ran my regression tests.  I have a test that does the following:

1. Create a new data set
2. Add some people ( data is now in edit state )
3. request `https://<domain>/#view/<dataset identifer>` ( some other dataset)
4. Validate  the presence of the confirmation dialog ("Do you want to leave this page?...")

Step four above is now failing with commit 838c35716a4667007990 the previous commit does not have this issue.

**Comment by laurenwalker** [comment]
This is fixed now

**Comment by vchendrix** [comment]
@laurenwalker  `2.0.0-rc6` this is still an issue if you click the organizational logo that goes to `https://<domain>`.  Also the use case that I described above is still an issue.

1. Create a new data set
2. Add some people ( data is now in edit state )
3. request `https://<domain>/#view/<dataset identifer>` ( some other dataset)
4. Validate  the presence of the confirmation dialog ("Do you want to leave this page?...")

**Comment by laurenwalker** [comment]
The issue is fixed when I test it. Make sure you have updated some files that you may have overridden in your deployment, in particular the router.js. Here are all the changes from the fix: https://github.com/NCEAS/metacatui/commit/838c35716a4667007990e9da8368fb29aeafd42f
